# Generated by Django 5.0 on 2024-01-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
