# Generated by Django 5.0 on 2024-02-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_line_2_alter_order_address_line_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
